server:
  http:
    addr: 127.0.0.1:8090
    timeout: 1s
  grpc:
    addr: 127.0.0.1:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/food?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    dial_timeout: 1s
jwt:
  secret: ToIZET+HX^a4Y$U3B%k{r{Yc=z4{%bi|
# 过期时间，单位h
#  expire_duration: 24h